### ISSUE TITLE
Add an option to ser/des that data in instance with Squash before writing it to the DataStore.

### ISSUE THREAD

**Issue by ghost** [MadStudioRoblox/ProfileStore#7]

**Comment by ghost** [comment]
Optional a function that needs to return a buffer and one that returns the data pattern, this would allow for more freedom on the devs side and the benefits of using buffers for saving data.

**Comment by LM-loleris** [comment]
I appreciate the interest, but this kind of feature would require to pretty much overhaul the whole module. You're welcome to make your own version though.
